[features]
seeds = false
skip-lint = false
[programs.localnet]
staking = "Ag8mEyesfLwYxSjvBuczmwhojP1BFpyWJLtPucFDvJfN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/helsin828/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
